"""
Plotting utilities for learning curves and policy visualisation.

Arrow directions map directly to the agent's greedy action in each cell.
A visit-count heatmap (generated by running the greedy policy for 1000
steps) is overlaid to show where the agent spends most of its time.
"""

import os

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

from src.environment import make_env
from src.models import mlp_forward
from src.utils import one_hot


# ── Plot colour palette ───────────────────────────────────────────────────────

COLORS = {"random": "#888888", "dqn": "#1976D2", "reinforce": "#E64A19"}

# Action → (dx, dy) in imshow coordinates (origin="upper")
# UP   (-row) → dy=-0.35   DOWN  (+row) → dy=+0.35
# LEFT (-col) → dx=-0.35   RIGHT (+col) → dx=+0.35
_ACTION_DX = {0:  0.00, 1:  0.00, 2: -0.35, 3:  0.35}
_ACTION_DY = {0: -0.35, 1:  0.35, 2:  0.00, 3:  0.00}


# ── Helpers ───────────────────────────────────────────────────────────────────

def get_runs(results: dict, agent: str, key: str) -> list:
    return [r["episode_rewards"] for r in results[agent][key]]


def mean_and_se(runs: list):
    """Return (mean, standard_error, x_indices) arrays."""
    min_len = min(len(r) for r in runs)
    arr  = np.array([r[:min_len] for r in runs])
    mean = arr.mean(axis=0)
    se   = arr.std(axis=0) / np.sqrt(len(runs))
    xs   = np.arange(min_len)
    return mean, se, xs


def get_best_key(results: dict, agent: str) -> str:
    """Return the hyperparameter key with the highest mean reward over the final 50 episodes."""
    best_key, best_val = None, -np.inf
    for key in results[agent]:
        runs  = get_runs(results, agent, key)
        score = np.mean([np.mean(r[-50:]) for r in runs])
        if score > best_val:
            best_val = score
            best_key = key
    return best_key


# ── Learning-curve plots ──────────────────────────────────────────────────────

def plot_mean_se(results: dict, plots_dir: str) -> None:
    """Plot 1: Mean ± Standard Error for the best config of each algorithm."""
    fig, ax = plt.subplots(figsize=(10, 5))

    mean, se, xs = mean_and_se(get_runs(results, "random", "default"))
    ax.plot(xs, mean, label="Random", color=COLORS["random"])
    ax.fill_between(xs, mean - se, mean + se, alpha=0.2, color=COLORS["random"])

    for agent in ["dqn", "reinforce"]:
        bk           = get_best_key(results, agent)
        mean, se, xs = mean_and_se(get_runs(results, agent, bk))
        ax.plot(xs, mean, label=f"{agent.upper()} (best: {bk})", color=COLORS[agent])
        ax.fill_between(xs, mean - se, mean + se, alpha=0.2, color=COLORS[agent])

    ax.set_xlabel("Episode")
    ax.set_ylabel("Episode Reward")
    ax.set_title("Mean ± Standard Error | Best Config per Algorithm | 10 Seeds")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()

    p = os.path.join(plots_dir, "plot1_mean_se.png")
    plt.savefig(p, dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: {p}")


def plot_individual_runs(results: dict, plots_dir: str) -> None:
    """Plot 2: All individual seed runs for the best config of each algorithm."""
    for agent in ["dqn", "reinforce"]:
        bk      = get_best_key(results, agent)
        runs    = get_runs(results, agent, bk)
        min_len = min(len(r) for r in runs)
        cmap    = cm.get_cmap("tab10", len(runs))

        fig, ax = plt.subplots(figsize=(10, 5))
        for i, run in enumerate(runs):
            seed = results[agent][bk][i]["seed"]
            ax.plot(run[:min_len], color=cmap(i), alpha=0.75, label=f"seed {seed}")

        ax.set_xlabel("Episode")
        ax.set_ylabel("Episode Reward")
        ax.set_title(f"{agent.upper()} — All 10 Individual Runs | {bk}")
        ax.legend(fontsize=7, ncol=2)
        ax.grid(True, alpha=0.3)
        plt.tight_layout()

        p = os.path.join(plots_dir, f"plot2_individual_{agent}.png")
        plt.savefig(p, dpi=150, bbox_inches="tight")
        plt.show()
        print(f"Saved: {p}")


def plot_hyperparam_sensitivity(results: dict, cfg: dict, plots_dir: str) -> None:
    """Plot 3: Hyperparameter sensitivity across all (lr, gamma) combinations."""
    lrs    = cfg["hyperparameters"]["learning_rates"]
    gammas = cfg["hyperparameters"]["discount_factors"]
    ls_map = {0.9: "-", 0.99: "--"}

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    for ax, agent in zip(axes, ["dqn", "reinforce"]):
        for gamma in gammas:
            for lr in lrs:
                key         = f"lr{lr}_gamma{gamma}"
                mean, _, xs = mean_and_se(get_runs(results, agent, key))
                ax.plot(xs, mean, linestyle=ls_map.get(gamma, "-"),
                        label=f"lr={lr}, γ={gamma}", alpha=0.85)
        ax.set_title(f"{agent.upper()} — Hyperparameter Sensitivity")
        ax.set_xlabel("Episode")
        ax.set_ylabel("Mean Episode Reward")
        ax.legend(fontsize=7)
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    p = os.path.join(plots_dir, "plot3_hyperparam_sensitivity.png")
    plt.savefig(p, dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: {p}")


# ── Policy visualisation ──────────────────────────────────────────────────────

def greedy_policy_grid(params, n_states: int, grid_size: int) -> np.ndarray:
    """Return a (grid_size, grid_size) array of greedy action indices."""
    policy = np.zeros((grid_size, grid_size), dtype=int)
    for s in range(n_states):
        sv = jax.device_put(one_hot(s, n_states))
        policy[s // grid_size, s % grid_size] = int(jnp.argmax(mlp_forward(params, sv)))
    return policy


def plot_policy_heatmap(params, agent: str, hp_key: str,
                        cfg_env: dict, seed: int, plots_dir: str) -> None:
    """
    Visualise the greedy policy as arrows overlaid on a visit-count heatmap.
    The visit map is built by running the greedy policy for max_steps × 5 steps.
    """
    grid_size = cfg_env["grid_size"]
    obstacles = set(map(tuple, cfg_env["obstacles"]))
    goal      = (grid_size - 1, grid_size - 1)
    n_states  = grid_size ** 2

    policy = greedy_policy_grid(params, n_states, grid_size)

    visit_map = np.zeros((grid_size, grid_size), dtype=float)
    env       = make_env(cfg_env, seed=seed)
    obs, _    = env.reset(seed=seed)
    for _ in range(cfg_env["max_steps"] * 5):
        r, c = divmod(obs, grid_size)
        visit_map[r, c] += 1
        obs, _, terminated, truncated, _ = env.step(int(policy[r, c]))
        if terminated or truncated:
            obs, _ = env.reset(seed=seed)
    env.close()

    fig, ax = plt.subplots(figsize=(7, 7))
    im = ax.imshow(visit_map, cmap="YlOrRd", origin="upper", interpolation="nearest")
    plt.colorbar(im, ax=ax, label="Visit count (greedy rollout)")

    for r in range(grid_size):
        for c in range(grid_size):
            if (r, c) in obstacles:
                ax.add_patch(plt.Rectangle(
                    (c - 0.5, r - 0.5), 1, 1, color="black", zorder=2
                ))
            elif (r, c) == goal:
                ax.add_patch(plt.Rectangle(
                    (c - 0.5, r - 0.5), 1, 1, color="#4CAF50", alpha=0.6, zorder=2
                ))
                ax.text(c, r, "G", ha="center", va="center",
                        fontsize=13, fontweight="bold", color="white", zorder=3)
            else:
                a  = int(policy[r, c])
                dx = _ACTION_DX[a]
                dy = _ACTION_DY[a]
                ax.annotate("", xy=(c + dx, r + dy), xytext=(c, r),
                            arrowprops=dict(arrowstyle="->", color="steelblue",
                                           lw=1.5, mutation_scale=12),
                            zorder=3)

    ax.scatter([0], [0], marker="*", s=250, color="gold", zorder=4, label="Start")
    ax.set_xlim(-0.5, grid_size - 0.5)
    ax.set_ylim(grid_size - 0.5, -0.5)
    ax.set_xticks(range(grid_size))
    ax.set_yticks(range(grid_size))
    ax.set_title(f"{agent.upper()} Greedy Policy | {hp_key} | seed={seed}")
    ax.legend(loc="lower right")
    plt.tight_layout()

    p = os.path.join(plots_dir, f"policy_{agent}_{hp_key}_seed{seed}.png")
    plt.savefig(p, dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: {p}")
